apiVersion: v1
kind: Service
metadata:
  name: demo-backend-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: demo-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend-deployment
spec:
  selector:
    matchLabels:
      app: demo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: demo-backend-container
        image: us.icr.io/demo/demo-backend:latest
        # Add the URL directly, tell the user where to get the items for the URL
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
